server:
  port: 8080  #教程中是80 本地测试不通过更换成8080  
  
#测试hystrix的  api接口中配置多个fallback时需要添加以下代码
#直接添加次属性会报错 必须在configBean中 配置 feignBuilder
#BEGIN
feign:
  hystrix:
    enabled: true  #开启
#END

eureka:
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    service-url:  #注册到集群中
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  
# 自定义属性  服务方的访问路径 ip+端口 方便修改
REST_URL_PREFIX: "http://localhost:8001"

# 测试变量是否能取到
restUrlSuffix: "http://localhost:8080"
